### ISSUE TITLE
Add-on Startup Failed

### ISSUE THREAD

**Issue by aadesouz** [Shirajuki/anki-redesign#80]
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.0-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-06 06:16:37

When loading Anki-redesign:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/aarondesouza/Library/Application Support/Anki2/addons21/308574457/__init__.py", line 11, in <module>
    from PyQt5.QtWidgets import QWidget
ModuleNotFoundError: No module named 'PyQt5'

**Comment by aadesouz** [comment]
The following add-ons failed to load: ⁨
[Anki-redesign](https://ankiweb.net/shared/info/308574457)⁩
They may need to be updated to support this version of Anki. Click the Check for Updates button to see if any updates are available.
You can use the Copy Debug Info button to get information that you can paste in a report to the add-on author.
For add-ons that don't have an update available, you can disable or delete the add-on to prevent this message from appearing.

**Comment by kvn1351** [comment]
@flippantbird Change that line to `from aqt.qt import QWidget` 

@Shirajuki They've moved all Qt modules to aqt now.

**Comment by aadesouz** [comment]
Perfect, thanks!!

**Comment by kvn1351** [comment]
@flippantbird The issue still exists in the codebase so keep it open pls

**Comment by kvn1351** [comment]
I've also fixed the config window but that isn't a one line change. I'll make a PR if time allows.

**Comment by AustinHasten** [comment]
I had luck resolving this by replacing "PyQt5" with "PyQt6" in \_\_init\_\_.py, and then using the script found here (https://stackoverflow.com/a/72658216/3261260) to replace all of the Qt5 enums with the Qt6 versions. No crashes on startup or when opening the configuration menu.

**Comment by ArcticDev78** [comment]
This issue is still present in Anki version 23.10.1

**Comment by chatterine** [comment]
> I had luck resolving this by replacing "PyQt5" with "PyQt6" in __init__.py, and then using the script found here (https://stackoverflow.com/a/72658216/3261260) to replace all of the Qt5 enums with the Qt6 versions. No crashes on startup or when opening the configuration menu.

Hi! How are you? I'm here because I'm having this issue as well, and I'm not much of a developer so I don't know how to fix it, sadly. Someone from Anki's Discord server told me I should ask you, so here it goes: could you please upload the code of your updated __init__.py file to Pastebin? Thanks!

**Comment by ArcticSpaceFox** [comment]
Any update on this?
